# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('students', models.IntegerField(default=0)),
                ('course_type', models.CharField(choices=[('L', 'Lab'), ('T', 'Theory')], max_length=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TeacherProfile')),
            ],
        ),
    ]
