# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-26 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coursepreference_tapreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=3)),
                ('avg_hours', models.IntegerField()),
                ('days', models.IntegerField()),
                ('approval', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TAProfile')),
            ],
        ),
    ]
